
spring:
  profiles:
    active: ${ACTIVE_PROFILES}
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_DEFAULT_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 24
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          time_zone: UTC
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml
    default-schema: ${POSTGRES_DEFAULT_SCHEMA}

rating-service:
  access-token: token
