version: '3.7'

services:
  postgres-todo:
    image: postgres
    container_name: postgres-todo
    restart: always
    env_file:
      - database.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - todo

volumes:
  postgres-data:

networks:
  todo:
    driver: bridge